### ISSUE TITLE
Why are the page margins in **em**?

### ISSUE THREAD

**Issue by rubemz** [joseph/Monocle#132]
context - in monocore.css:

``` css
div.monelem_sheaf {
  top: 1em;
  left: 1em;
  bottom: 1em;
  right: 1em;
}
```

It seems to cause some rounding problems... 
For example, using chrome it converts these values to 13.333304..px. And then it leads to monolean_sheaf to have a different width (1px) than the inner iframe due to these roundings. And, as result, some of the internal calculations fail. For example, the locus search test when searching for gremlin is failing since these differences affect the page calculation. 

Any thoughts? should these values be in pixels?
